# Generated by Django 2.2.11 on 2020-04-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_auto_20200415_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='subject',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
